version: '3.7'
services:
  mongo-rs0-1:
    image: "mongo-start"
    container_name: mongo-rs0-1
    build: ./mongo-rs0-1
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-rs0-1/data:/data/db
    depends_on:
      - "mongo-rs0-2"
      - "mongo-rs0-3"

  mongo-rs0-2:
    image: "mongo:3.2-jessie"
    container_name: mongo-rs0-2
    command: --replSet rs0 --smallfiles --oplogSize 128
    ports:
      - "27018:27017"
    volumes:
      - ./mongo-rs0-2/data:/data/db

  mongo-rs0-3:
    image: "mongo:3.2-jessie"
    container_name: mongo-rs0-3
    command: --replSet rs0 --smallfiles --oplogSize 128
    ports:
      - "27019:27017"
    volumes:
      - ./mongo-rs0-3/data:/data/db

  setup-rs:
    image: "setup-rs"
    container_name: mongo_setup
    build: ./setup
    depends_on:
      - "mongo-rs0-1"

  adminmongo:
    image: "mrvautin/adminmongo"
    container_name: adminmongo
    ports:
      - "1234:1234"
